// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Data.Models;

public partial class Book
{
    public int BookId { get; set; }

    public string Titel { get; set; }

    public string Auther { get; set; }

    public string ISPN { get; set; }

    public int PuplishedYear { get; set; }

    public string BookStatus { get; set; }

    public DateTime? CreatedAt { get; set; }
    [JsonIgnore (Condition = JsonIgnoreCondition.WhenWritingNull)]
    public virtual ICollection<Borrowing> Borrowings { get; set; } = new List<Borrowing>();
}