// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Borrowing
{
    public int BorrowId { get; set; }

    public DateTime BorrowDate { get; set; }

    public DateTime ReturnDate { get; set; }

    public string BorrowStatus { get; set; }

    public int BookId { get; set; }

    public int MemberId { get; set; }

    public virtual Book Book { get; set; }

    public virtual Member Member { get; set; }
}